services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hw03
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
